name: 'Docker Build and Push'
description: 'Build and push Docker image to a container registry'

inputs:
  registry:
    description: 'Container registry URL (e.g., ghcr.io, docker.io)'
    required: true
  username:
    description: 'Registry username'
    required: true
  password:
    description: 'Registry password or token'
    required: true
  image-name:
    description: 'Docker image name (without registry prefix)'
    required: true
  tag:
    description: 'Docker image tag'
    required: false
    default: 'latest'
  context:
    description: 'Build context path'
    required: false
    default: '.'
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: 'Dockerfile'
  build-args:
    description: 'Build arguments (one per line, KEY=VALUE format)'
    required: false
    default: ''
  push:
    description: 'Push the image to registry'
    required: false
    default: 'true'

outputs:
  image:
    description: 'Full image reference (registry/image:tag)'
    value: ${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.tag }}
  digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build and Push Docker Image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.tag }}
        build-args: ${{ inputs.build-args }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
