name: 'Docker Cleanup'
description: 'Clean up Docker resources'

inputs:
  prune-images:
    description: 'Prune unused images'
    required: false
    default: 'true'
  prune-all:
    description: 'Run docker system prune (all unused resources)'
    required: false
    default: 'false'
  image-age:
    description: 'Only prune images older than this (e.g., 168h)'
    required: false
    default: '168h'

runs:
  using: 'composite'
  steps:
    - name: Docker cleanup
      shell: bash
      run: |
        if [ "${{ inputs.prune-all }}" == "true" ]; then
          echo "::notice title=Pruning::All unused Docker resources"
          docker system prune -f --filter "until=${{ inputs.image-age }}" 2>/dev/null || true
        elif [ "${{ inputs.prune-images }}" == "true" ]; then
          echo "::notice title=Pruning::Images older than ${{ inputs.image-age }}"
          docker image prune -f --filter "until=${{ inputs.image-age }}" 2>/dev/null || true
        fi
        
        echo "::notice title=Disk Usage::"
        docker system df
