name: 'Set Image Tag'
description: 'Determine Docker image tag based on strategy'

inputs:
  strategy:
    description: 'Tagging strategy: latest, sha, branch, tag, semver, custom'
    required: false
    default: 'latest'
  custom-tag:
    description: 'Custom tag value (when strategy is custom)'
    required: false
    default: ''
  prefix:
    description: 'Prefix to add to the tag'
    required: false
    default: ''
  suffix:
    description: 'Suffix to add to the tag'
    required: false
    default: ''

outputs:
  tag:
    description: 'The computed image tag'
    value: ${{ steps.tag.outputs.tag }}

runs:
  using: 'composite'
  steps:
    - name: Determine tag
      id: tag
      shell: bash
      run: |
        case "${{ inputs.strategy }}" in
          "latest")  TAG="latest" ;;
          "sha")     TAG="${GITHUB_SHA:0:7}" ;;
          "branch")  TAG=$(echo "${GITHUB_REF_NAME}" | sed 's/[^a-zA-Z0-9._-]/-/g') ;;
          "tag")
            if [[ "$GITHUB_REF" == refs/tags/* ]]; then
              TAG="${GITHUB_REF_NAME}"
            else
              echo "::warning title=No Tag::Falling back to latest"
              TAG="latest"
            fi ;;
          "semver")
            if [[ "$GITHUB_REF" == refs/tags/v* ]]; then
              TAG="${GITHUB_REF_NAME#v}"
            else
              TAG="0.0.0-${GITHUB_SHA:0:7}"
            fi ;;
          "custom")
            TAG="${{ inputs.custom-tag }}"
            [ -z "$TAG" ] && echo "::error title=Missing::custom-tag required" && exit 1 ;;
          *)
            echo "::error title=Invalid::Unknown strategy ${{ inputs.strategy }}"
            exit 1 ;;
        esac
        
        FULL_TAG="${{ inputs.prefix }}${TAG}${{ inputs.suffix }}"
        echo "tag=$FULL_TAG" >> $GITHUB_OUTPUT
        echo "::notice title=Tag::$FULL_TAG"
