name: 'Create Environment File'
description: 'Create an environment file with key-value pairs for Docker Compose or other applications'

inputs:
  file-path:
    description: 'Path to the environment file to create'
    required: false
    default: '.env'
  working-directory:
    description: 'Working directory where the file will be created'
    required: false
    default: '.'
  variables:
    description: 'Environment variables in KEY=VALUE format (one per line)'
    required: true
  overwrite:
    description: 'Overwrite existing file if it exists'
    required: false
    default: 'true'
  mode:
    description: 'File permissions mode'
    required: false
    default: '600'

outputs:
  file-path:
    description: 'Full path to the created environment file'
    value: ${{ steps.create.outputs.env_file }}

runs:
  using: 'composite'
  steps:
    - name: Create environment file
      id: create
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -f "${{ inputs.file-path }}" ] && [ "${{ inputs.overwrite }}" != "true" ]; then
          echo "::warning title=File Exists::Environment file already exists, skipping"
          exit 0
        fi
        
        echo '${{ inputs.variables }}' > "${{ inputs.file-path }}"
        chmod "${{ inputs.mode }}" "${{ inputs.file-path }}"
        
        echo "::notice title=Created::Environment file ${{ inputs.file-path }}"
        echo "env_file=${{ inputs.working-directory }}/${{ inputs.file-path }}" >> $GITHUB_OUTPUT
