name: 'Docker Registry Login'
description: 'Log in to a Docker container registry'

inputs:
  registry:
    description: 'Container registry URL'
    required: true
  username:
    description: 'Registry username'
    required: true
  password:
    description: 'Registry password or token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Confirm login
      shell: bash
      run: echo "::notice title=Logged In::Successfully authenticated to ${{ inputs.registry }}"
